### ISSUE TITLE
Async requests are not handled correctly

### ISSUE THREAD

**Issue by matt-kruse** [matt-kruse/alexa-app#1]
If an intent handler tries to launch an async request and respond to alexa when the async call completes, this doesn't work. The (empty) response is already flushed. The lib should allow for the common need of using async requests in intent requests.

**Comment by psayre23** [comment]
I see a couple ways to do this:
1) Create a new function called .done() or .send(), which internally sends back the json.
2) When a function is called that will send a response, internally wait till next tick and send the json.
3) Have a function .waitUntil() that returns a callback to call when your ready to send.

Option 3 and 2 are backwards compatible. Option 1 is closer to how node works internally, but breaks the abstraction a little bit. Option 3 is the easiest to implement, keeps the API simple, and allows the most flexibility to the developer.

**Comment by psayre23** [comment]
I just submitted two pull requests for option 3. Personally, I like the one with promises, but native promises were only added recently in v0.12. You'd need to add a polyfill (and therefore a dependency) for support of v0.10 and lower.

**Comment by jaredalexander** [comment]
Thanks!






On Mon, Jun 1, 2015 at 2:45 PM -0700, "psayre23" <notifications@github.com> wrote:












I just submitted two pull requests for option 3. Personally, I like the one with promises, but native promises were only added recently in v0.12. You'd need to add a polyfill (and therefore a dependency) for support of v0.10 and lower.

**Comment by matt-kruse** [comment]
Fixed in version 2.0, to be released soon. Intent handlers can now return false, and resolve the response promise whenever they are done with their work.
