### ISSUE TITLE
Wrong behavior for undefined AudioPlayer event handler

### ISSUE THREAD

**Issue by fremail** [matt-kruse/alexa-app#105]
If you don't set event handlers for all AudioPlayer events, the skill will fail because the app will end silently.

It should return even an empty response (without directives). So answer `response.send();` would be enough instead of throwing an exception.

I'm not able to post additional data now.

Happy New Year! ^__^

**Comment by dblock** [comment]
Looks like a legit problem in need of a test and a fix ;)

**Comment by trayburn** [comment]
PR created that proves and fixes this behavior.  Now responds with a simple (no directives or speech) response, on a promise which is fulfilled.  Should be more than sufficient to satisfy Amazon's expectations of handling AudioPlayer events.

**Comment by dblock** [comment]
Via https://github.com/matt-kruse/alexa-app/pull/108.
