### ISSUE TITLE
What's the utility of response.session(key, val)

### ISSUE THREAD

**Issue by OverloadUT** [matt-kruse/alexa-app#13]
I am trying to wrap my head around the idea behind turning the session attributes on the response in to a setter function rather than just neatly exposing the object.

You don't have a getter function set up, so when the user needs to read values from the attributes he can't without going in and accessing ```request.request.sessionAttributes``` anyway.

Since the setter isn't providing any utility, maybe it should be removed and the interface simplified? It seems like it's a setter for setter's sake.

**Comment by matt-kruse** [comment]
request.session(key) will return the session value, and response.session(key,value) will set a new one. You can still get to the sessionAttributes directly, but I find those utility methods to be more straight-forward.

**Comment by OverloadUT** [comment]
But that still means it's impossible to get the current sessionsAttributes staged in the response via your utility method. At the very least response.session(key) should get the current value.

In javascript and especially node I'm not used to seeing getter and setter methods for no reason. Typically an object is just exposed and the user uses that directly. I only see downsides of this method, such as losing out on all operators. Consider the semantic readability of this (this would assume you would make response.session a getter as well):

```js
// Using methods
response.session('totalScore', response.session('totalScore') + response.session('roundScore'));

// Using the object
response.session.totalScore += response.session.roundScore;
```

It's not huge yeah, but the latter is what you see everywhere in Javascript. By forcing the use of methods to set a variable, you lose out on all of the operators. For example, you can't `delete` a parameter from the object right now. You can either set it to `null` (which is not the same as non-existent, and will actually get put in to the JSON string) or set it as `undefined` which is also, paradoxically, not the same as actually having it undefined. Javascript is kind of lame like that.

At the end of the day it's not a big deal so long as you leave response.response.sessionAttributes available to manipulate directly; I'm just trying to give feedback on making this thing a rock solid module that follows as close to node module standards (let's be honest and use that term very loosely ;) )

**Comment by matt-kruse** [comment]
Like you said, everything is still exposed. The session methods are just shortcuts for common operations. In 2.1 I've added a response.clearSession() function, which either clears all response session data, or if passed a key it will clear just that key. I will add the ability to call response.session(key) as a getter, for convenience.

**Comment by OverloadUT** [comment]
Cool, that'll work! If I want to globally disable the feature I should just be able to put response.clearSession() in pre(), right?

**Comment by matt-kruse** [comment]
Or like I say in the other issue, app.persistentSession=false to disable it entirely. :)
