### ISSUE TITLE
whitespace

### ISSUE THREAD

**Issue by simplydallas** [matt-kruse/alexa-app#18]
Schema generation adds extra white space when skipping an optional item.  An example would be "fu {bar|} baz"  will generate "fu bar baz" and "fu   baz" with extra white space where it skipped bar.  I am trimming that down with regex replacement but it would be best if skipped pieces of a generated string do not add white space.

**Comment by matt-kruse** [comment]
You can avoid this by changing how you do your expression. Try:
"fu {bar |}baz"
The library can't guess your intent, and it shouldn't assume you mean something other than what you write. So the syntax above is preferred over collpasing whitespace, IMO.

**Comment by simplydallas** [comment]
I do not think it needs know intentions to when it comes to white space.  There is no situation where the utterances API benefits from whitespace beyond a single space character.  This includes the tabs that the schema generation currently creates as well.  There are advantages to cleaning the white space though, as some of the apps I am running struggle a bit with the 200,000 character mark.

appname.utterances().replace(/\t/g, ' ').replace(/  +/g, ' ').replace(/[-]/g, ' ')  does the trick without making the regex a complex multimatch.  I will keep using that if you prefer not to collapse white space in the module.  I appreciate the library.  It is much cleaner than what I had pieced together before.

**Comment by matt-kruse** [comment]
You don't need to post-process to collapse the whitespace if you use the syntax like I mentioned above, where the optional whitespace is included in the {} itself.
I'll take a look at this when I do my next update, but I wanted to be clear that you could avoid the double whitespace now using the existing syntax.

**Comment by simplydallas** [comment]
Thank you Matt.  I did notice that whitespace could be in the options and also tested it and it works well.  It didn't seem intuitive and I wanted to kill off the generated tabs so I was using replace already and wanted to mention it to you here.  Going to close this though.  My bigger issue is the other report, which is number formats having hyphens.  That one actually impacts the functionality of the final Alexa app.

**Comment by matt-kruse** [comment]
What is wrong with the tabs? I find them easier than a space character to separate intent names from the utterance, and the tab is valid.

**Comment by matt-kruse** [comment]
Fixed in 2.1.4

**Comment by simplydallas** [comment]
Thanks for the quick fixes/adjustments Matt.  As far as the generated tabs, nothing is wrong with them.  I was just replacing them for personal preference.  I wanted my utterances to be as compact as possible.
