### ISSUE TITLE
how to know which utterance is triggered?

### ISSUE THREAD

**Issue by rstormsf** [matt-kruse/alexa-app#19]

**Comment by matt-kruse** [comment]
You don't get to know. That is a limitation of the Alexa Skills Kit. You only get to know which intent was triggered.

**Comment by rstormsf** [comment]
:-( Thank you for your answer. Maybe I can just save to the whole variable and then access as `req.slot` ??
how would you handle this if I have the following utterance?
```
"utterances":["{Can you |}{get a taxi|get taxi|get a cab|order taxi}"]
```
so it can support nested utterances? 
or alexa utterance don't allow to have nested vars?

**Comment by rstormsf** [comment]
Looks like it's not possible.
Ok, I can access `speeachOutput` how about access which intent was triggers in `postRequest` function?
