### ISSUE TITLE
Increase timeout

### ISSUE THREAD

**Issue by rstormsf** [matt-kruse/alexa-app#21]
How do I increase timeout response if there is slow internet connection?

**Comment by matt-kruse** [comment]
You can't. This is a limitation of the Echo/Alexa platform. Please familiarize yourself with the Alexa SDK, since this module is built on top of it.

**Comment by rstormsf** [comment]
Thank you very much for your quick support. I was participating at TechCrunch hackathon and as you probably know during whole last week Amazon Lambda was down, so we had no choice other than using your great backend. I really like it.
If we won something, you would definitely got something from us.
Unfortunately, we didn't win anything. 
Also, Alexa gave us too many problems - it doesn't work when 159 teams are around and a lot of radio waves going on. It simply doesn't see any Wifi. 
http://devpost.com/software/alexa-club
https://github.com/rstormsf/alexaclub

Since it was a hackathon - the code is not that good
