### ISSUE TITLE
Need a way to handle custom slot types

### ISSUE THREAD

**Issue by colinsullivan** [matt-kruse/alexa-app#25]
Amazon is now recommending we use custom slot types instead of the "LITERAL" type.  More here:

[https://developer.amazon.com/public/solutions/alexa/alexa-skills-kit/docs/alexa-skills-kit-interaction-model-reference#Custom Slot Type Syntax](https://developer.amazon.com/public/solutions/alexa/alexa-skills-kit/docs/alexa-skills-kit-interaction-model-reference#Custom Slot Type Syntax)

Basically, in our utterances we don't put the example variables, so for example:

```js
app.intent("whereIsIntent", {
  slots: {
    "NAME": "LIST_OF_NAMES",
  },
  utterances: [
    "where is {mom|dad|my brother|my sister|my daughter|my son|NAME}"
  ],
  function (req, res) {
    var name = request.slot("NAME");

    response.say("I don't know where " + name + "is.");
  }
});
```

The utterances generated should be:

```plaintext
whereIsIntent   where is {NAME}
```

And then perhaps we could use a separate method on the app, along with `schema` and `utterances`, something like `customtype(slotname)`?  Which would output the following:

```plaintext
mom
dad
my brother
my sister
my daughter
my son
```

I still think there is value in your combinatorics stuff, and also perhaps it can be re-evaluated as it seems this is exactly what they are trying to obviate with the custom slot type feature.

**Comment by colinsullivan** [comment]
Is this essentially what you implemented as app.dictionary ?

**Comment by jpriebe** [comment]
There is definitely value in the combinatorics even with the custom slots.  I don't think that the custom dictionaries are intended to handle things like 

"{what is the|what's the|check the} status"

I don't think you'd use a custom slot in this case.  And capturing all the variations in phrasing is much easier with these macro expansions.

**Comment by colinsullivan** [comment]
Yep, makes sense.  In your example, there is no slot because there is no parameter (you don't care how they said it, you just want the statusIntent to run).

**Comment by mutexkid** [comment]
We now support custom slot types as of #68 . See updated README for details - marking as closed.
