### ISSUE TITLE
move generateUtterances to its' own npm module

### ISSUE THREAD

**Issue by mreinstein** [matt-kruse/alexa-app#26]
It seems that the `generateUtterances` function is very well contained and is probably useful outside of `alexa-app`. Would you be open to moving this to  new npm module, say `alexa-utterances`?

I'd be happy to pull this out into its' own module if that would be accepted as a PR

**Comment by matt-kruse** [comment]
Brilliant - yes! I think alexa-utterances sounds like a perfect idea, and it can incorporate the other changes in #23 so the utterances examples aren't so exhaustive. If you want to create, own, and maintain the alexa-utterances feel free to publish it and I will change my code to just use it. :)

**Comment by mreinstein** [comment]
still very much a work in progress, but I've copied the relevant code in. 

https://github.com/mreinstein/alexa-utterances

I still need to expose the appropriate functions as exports, provide a README with examples, some basic tests before it's usable.

**Comment by mreinstein** [comment]
@matt-kruse I've got this finished. I've also published this to npm, and added you as a collaborator in both github and npm:
* https://github.com/mreinstein/alexa-utterances
* https://www.npmjs.com/package/alexa-utterances

I guess next steps are getting the improved (reduced) utterance generation PR.

**Comment by matt-kruse** [comment]
Done in alexa-app 2.1.5 

Thank you @mreinstein !
