### ISSUE TITLE
support account linking card type

### ISSUE THREAD

**Issue by mreinstein** [matt-kruse/alexa-app#36]
There's a new card type, called `LinkAccount`. It enables authenticating your own oauth2 service with alexa skills:

https://developer.amazon.com/public/solutions/alexa/alexa-skills-kit/docs/linking-an-alexa-user-with-a-user-in-your-system#Adding Account Linking Logic to the Service for Your Skill

 It would be nice to support this in `alexa-app`. I might send a PR for this if I can find some time.

**Comment by christianewillman** [comment]
@matt-kruse @mreinstein I took a stab with this in PR #38. Also see PR #37

**Comment by matt-kruse** [comment]
Resolved in 2.3.0
