### ISSUE TITLE
Allow configurable error responses

### ISSUE THREAD

**Issue by OverloadUT** [matt-kruse/alexa-app#4]
There are a few verbal responses that can come directly from the alexa-app module, that cannot be configured by the developer. I would prefer to have control over any possible verbal response that comes from my app, so either kicking off an error event that can be implemented or allowing those responses to be configured would be great!

**Comment by matt-kruse** [comment]
Thanks, I added an error handler function in version 2, to be released soon. I also pulled the default message strings up into a configurable messages section.
