### ISSUE TITLE
Consider adding a license

### ISSUE THREAD

**Issue by techpeace** [matt-kruse/alexa-app#42]
Hi there! This is awesome stuff. I was hoping to incorporate some of this into something I'm working on, but I noticed there wasn't a license. I was wondering if you wouldn't mind [adding one to the project](http://choosealicense.com/) so that I could do that and contribute any improvements back upstream. Thanks!

**Comment by OverloadUT** [comment]
The package.json file indicates that the licence is MIT :)

**Comment by matt-kruse** [comment]
I added LICENSE.md to the project to make it clear.

**Comment by techpeace** [comment]
Oh thanks, didn't see that! Appreciate it. :)
