### ISSUE TITLE
Reference the users location

### ISSUE THREAD

**Issue by aBigSchwein** [matt-kruse/alexa-app#50]
I have a skill that needs location based services. Ex: "Alexa, what's the nearest store to my location?"

Is there a legit intent or method to reference otherwise I was planning on using the request.connection.remoteAddress value. Does the alexa-app request object support that functionality?

**Comment by OverloadUT** [comment]
There is no support for getting the user's location unfortunately.

Using request.connection.remoteAddress will not work, as all requests to your endpoint come from the Alexa cloud in AWS's US-East region, and not from the Echo devices themselves.

You would probably need to ask the user to define their location.

**Comment by aBigSchwein** [comment]
Strange, I thought that might be the case.

It's weird tho that the documentation for ASK states these examples: 
 “Alexa, ask StubHub what events are happening this weekend near me?” 
 “Alexa, ask Glympse, when will Jack get here?”

**Comment by OverloadUT** [comment]
In both of those cases I expect that the app is linked to the user's account, which likely has "home" preferences already set. Definitely for Glympse at least.

**Comment by aBigSchwein** [comment]
Damn. Okay thanks man!
