### ISSUE TITLE
Card subtitle deprecated?

### ISSUE THREAD

**Issue by efung** [matt-kruse/alexa-app#52]
The API for including a card has an optional `subtitle` argument. But it doesn't seem to do anything. Looking at [this forum post](https://forums.developer.amazon.com/forums/thread.jspa?messageID=16917), this parameter may have been removed from the Alexa Skills API? The subtitle on cards is now the skill name.

**Comment by mutexkid** [comment]
@efung yes, subtitle has been deprecated. We've removed support for passing a subtitle as an argument to the card method as of https://github.com/matt-kruse/alexa-app/commit/8ff5245869d2360162edf75e4f81aea5c4ecf479 h/t @rickwargo
