### ISSUE TITLE
Standard Card type with Images

### ISSUE THREAD

**Issue by jejernig** [matt-kruse/alexa-app#53]
there seems to be no attribute to the response.card() function to allow for the insertion of images. Or any card type other than "Simple"

something like this would work?

`	this.standardCard = function(title, content, smallImageUrl, largeImageUrl){
			this.response.response.card = {"type": "Standard", "title": title, "content":SSML.cleanse(content), "image": {"smallImageUrl" smallImageUrl, "largeImageUrl": largeImageUrl} };
	}`
https://developer.amazon.com/public/solutions/alexa/alexa-skills-kit/docs/providing-home-cards-for-the-amazon-alexa-app

**Comment by jejernig** [comment]
issued a pull request 

https://github.com/matt-kruse/alexa-app/pull/54

**Comment by mutexkid** [comment]
Closing - we currently support standard cards as of https://github.com/matt-kruse/alexa-app/commit/18bb58e9d9383ff591e85a410187004d60502706
