### ISSUE TITLE
Exceptions in intent handler functions are "swallowed" by API

### ISSUE THREAD

**Issue by KevinEady** [matt-kruse/alexa-app#6]
Intent request function calls are in a [try-catch block](https://github.com/matt-kruse/alexa-app/blob/3887d3535c7857fecd6049dacc9540227963ed2c/index.js#L100-108). If an exception occurs, the default response is returned, provided that the response was not modified prior to exception. I see that version 2.0 has better error messages & handling, so i just wanted to verify that this is resolved?

**Comment by matt-kruse** [comment]
Yes, version 2.0 has the ability to define a handler that will be passed any exception.
