### ISSUE TITLE
.eslintrc should have extension

### ISSUE THREAD

**Issue by GitTom** [matt-kruse/alexa-app#62]
This is nit-picky, but the use of an extensionless eslint is deprecated, and it should be super simple to change.

> v1.10.0 introduces the ability to use configuration files in different formats. Instead of the regular .eslintrc file, you can use a JavaScript (.eslintrc.js), a YAML file (.eslintrc.yml or .eslintrc.yaml), or a JSON file (.eslintrc.json). **We are formally deprecating use of the .eslintrc extensionless configuration file format in favor the format-specific versions.** Don't worry, we'll still support .eslintrc files for a long time, but we'd like to encourage everyone to move to the new file formats as you'll get advantages such as syntax highlighting and error detection with many editors.

(bold added by me)

**Comment by mutexkid** [comment]
Nice, thanks for the heads up on this! Feel free to submit a PR fixing.

**Comment by GitTom** [comment]
I'm not actually using alexa-app (yet) and am rather a git newbie so I'll leave that to others.

**Comment by mutexkid** [comment]
https://github.com/matt-kruse/alexa-app/commit/b2a2571f6ddd93d99f8952a06a0aace67d841c83
