### ISSUE TITLE
Add NewSession event

### ISSUE THREAD

**Issue by OverloadUT** [matt-kruse/alexa-app#7]
There is a handy parameter in an Alexa request, ```session.new```, that tells the app that this request represents a brand new session.

I would like to be able to register an event handler for when a new session is started to do certain session setup tasks. Right now the only way to do this would be to check that parameter in every intent handler plus the launch handler and call the same function in each case.

**Comment by matt-kruse** [comment]
With the pre() method in version 2.1 coming soon, it will be easy to do "new session" kind of functionality. I think this is an okay fix for this request, unless you think a dedicated newSession() method would be more useful.

**Comment by OverloadUT** [comment]
Nah, after you proposed the pre() hook, I realized that this functionality could just go in there when a developer needs it.
