### ISSUE TITLE
Question about sessions

### ISSUE THREAD

**Issue by Snecx** [matt-kruse/alexa-app#72]
Hello

Maybe i'm to silly but i can't get sessions to work.
I have to intents. intent1 and intent2.

If intent1 is called i like to set a session var like which = 1, so i have tried to set with response.session('which','1') or request.session('which','1')

If intent2 is now called i like to read this var so i have tried with var sess = response.session('which')
or var req = request.session('which')

I only get 'undefined' or the error 'key not found on session attributes: which [TypeError: Cannot read property 'which' of undefined]'

What i'm doing wrong?

**Comment by dblock** [comment]
This is fairly old. Have you resolved your issue @Snecx? I am going to close it, but if you have a repro please reopen the issue.
