### ISSUE TITLE
response.clear() may result in incorrect outputSpeech type

### ISSUE THREAD

**Issue by wthomsen** [matt-kruse/alexa-app#75]
Calling `response.clear()` completely resets the outputSpeech object on the json response. If one subsequently calls `response.say('This was called after clear.')`, the response json will look something like this

```
...
"outputSpeech": {
  "type": "PlainText",
  "text": "",
  "ssml": "<speak>This was called after clear.</speak>"
}
...
```

Perhaps when calling `response.say()`, the outputSpeech type should be checked or re-assigned.

**Comment by rickwargo** [comment]
Agreed. PlainText is a subset of SSML (simply wrapped in a speech tag). Perhaps .clear() should maintain that consistency and set the type to SSML instead of PlainText as .say() automatically puts all output in SSML. I'll submit a pull request.

**Comment by dblock** [comment]
Fixed via https://github.com/rickwargo/alexa-app/commit/3f48cd4682b7e46e958544f94ce8b982ae24fbf6.
