### ISSUE TITLE
Error when uploading alexa-app to aws lamba

### ISSUE THREAD

**Issue by siddhartha-lahiri** [matt-kruse/alexa-app#78]
Hi,

I am trying to create a basic alexa-app and upload the zip file to lambda.
I have used generator-lambda to create a basic skeleton.

This is the error I keep on getting

```
{
  "errorMessage": "Cannot read property 'new' of undefined",
  "errorType": "TypeError",
  "stackTrace": [
    "new alexa.request (/var/task/node_modules/alexa-app/index.js:149:29)",
    "/var/task/node_modules/alexa-app/index.js:227:21",
    "tryCatcher (/var/task/node_modules/alexa-app/node_modules/bluebird/js/main/util.js:26:23)",
    "Promise._resolveFromResolver (/var/task/node_modules/alexa-app/node_modules/bluebird/js/main/promise.js:480:31)",
    "new Promise (/var/task/node_modules/alexa-app/node_modules/bluebird/js/main/promise.js:70:37)",
    "request (/var/task/node_modules/alexa-app/index.js:226:12)",
    "handler (/var/task/node_modules/alexa-app/index.js:357:10)"
  ]
}
```

**Comment by PaeP3nguin** [comment]
Try your skill out anyways. I find that the error only occurs on upload and testing in Lambda, but the skill itself works just fine. :/

**Comment by OverloadUT** [comment]
That is likely because you haven't changed the Test payload in Lambda. The default one is not an Alexa payload. You can change it to a simple LaunchRequest or something as a good way to sanity check that the uploaded codeworks.

**Comment by dblock** [comment]
Closing this, please let us know if you're still having issues @siddhartha-lahiri.

**Comment by fremail** [comment]
@dblock I got this error.

I have an app uploaded to Lambda.

The error is caused on getting `AudioPlayer` events. I got it twise: one for `AudioPlayer.PlaybackStarted` and one for `AudioPlayer.PlaybackFinished` I suppose.

```
{
    "errorMessage": "Cannot read property 'new' of undefined",
    "errorType": "TypeError",
    "stackTrace": [
        "new alexa.request (/var/task/node_modules/alexa-app/index.js:219:27)",
        "/var/task/node_modules/alexa-app/index.js:317:18",
        "tryCatcher (/var/task/node_modules/alexa-app/node_modules/bluebird/js/main/util.js:26:23)",
        "Promise._resolveFromResolver (/var/task/node_modules/alexa-app/node_modules/bluebird/js/main/promise.js:483:31)",
        "new Promise (/var/task/node_modules/alexa-app/node_modules/bluebird/js/main/promise.js:71:37)",
        "request (/var/task/node_modules/alexa-app/index.js:316:10)",
        "handler (/var/task/node_modules/alexa-app/index.js:448:8)"
    ]
}
```

**Comment by dblock** [comment]
Maybe ^^^ should go into that PR. It's by no means finished, seems like you're hitting issues from that?
