### ISSUE TITLE
Need a way to reject requests based on criteria

### ISSUE THREAD

**Issue by OverloadUT** [matt-kruse/alexa-app#8]
One common thing that I want to do at the beginning of my Alexa apps is to validate that the request has the proper AppID.

It would be nice if there were a way to do validation on a request before it moves forward with the rest of the logic.

I could see you implementing a built-in appID validation feature, or simply provide a way for the module user to provide a validation method that has the opportunity to kill the session with a response before it moves on to the other event types.

**Comment by matt-kruse** [comment]
What about pre() and post() functions that the user can define that can run for every request? That way you could add the appId check and even the new session check in the pre(). Would that be sufficient, or do you think it really needs separate API methods for appId check, new session, etc?

**Comment by OverloadUT** [comment]
That would certainly be sufficient!

**Comment by matt-kruse** [comment]
This will be included in version 2.1.
