### ISSUE TITLE
Continued Dev?

### ISSUE THREAD

**Issue by wlwise** [matt-kruse/alexa-app#80]
Hey Matt - it looks like Amazon has released the ASK for audio playback.  Are you planning to upgrade to accommodate and/or continue dev on this project?

**Comment by iammoen** [comment]
I would also like to know the answer to that. Even if you don't, thanks for your initial dev on this, it helped tremendously on so many things.

**Comment by matt-kruse** [comment]
I don't have any plans to add more functionality to alexa-app myself at this time. My goal was to get the community to maintain and enhance this project as it goes forward. I have a few collaborators already on this project, but it seems like they are not active anymore either. 
I would like it to continue being maintained, and the best way for that to happen is to get more people who are interested in it to contribute PR's and/or become collaborators to move it forward.

**Comment by ztolley** [comment]
Just to add my view. There's a bunch of new things just announced and not seen much activity here for a while. Is no one going to pick up the ball?

**Comment by wlwise** [comment]
We are making a bunch of updates to handle audio but aren't ready to submit yet.  Should be ready in a few weeks though.

**Comment by ztolley** [comment]
Then I take it back. I've looked that stuff that comes from amazon an its just long winded, compared this Alexa-app which is very 'express' like which makes it so much easier for node hacks

**Comment by dblock** [comment]
Here hear. Happy to help merge PRs for whatever functionality. Closing this one.
