### ISSUE TITLE
How do you add a context object to the request to enable audioplayer?

### ISSUE THREAD

**Issue by wschaeferiii** [matt-kruse/alexa-app#81]
With the [new long form audio feature](https://developer.amazon.com/public/community/post/Tx1DSINBM8LUNHY/New-Alexa-Skills-Kit-ASK-Feature-Audio-Streaming-in-Alexa-Skills) utilizing the audio player directives, how do you extend/add a context object to an intent request?

I can add the directives to the response, but the Alexa Skills Kit needs the request object to look like this:

{
  "version": "string",
      "session": {
         "new": true,
         "sessionId": "string",
      "application": {
         "applicationId": "string"
       },
       "attributes": {
          "string": {}
        },
      "user": {
          "userId": "string",
          "accessToken": "string"
       }
    },
    "context": {
        "System": {
             "application": {
                    "applicationId": "string"
             },
         "user": {
              "userId": "string",
              "accessToken": "string"
          },
         "device": {
              "supportedInterfaces": {
                  "AudioPlayer": {}
               }
           }
         },
      "AudioPlayer": {
           "token": "string",
           "offsetInMilliseconds": 0,
           "playerActivity": "string"
        }
   },
  "request": {}
}

Can you use the `app.pre()` or `app.post` library features to add the context object seen above?

**Comment by dblock** [comment]
I think https://github.com/matt-kruse/alexa-app/pull/88 would resolve this. Closing the issue, see the PR for anything missing.
