### ISSUE TITLE
Pre chained with request

### ISSUE THREAD

**Issue by tekkkon** [matt-kruse/alexa-app#82]
If I do a check in the app.pre() and it failed, I expect it just response the error message in app.pre() and terminate the request. But turned out, it sent out response in app.pre(), and still keep running the intent request. 

Any thoughts?

**Comment by rickwargo** [comment]
One of the common purposes of using app.pre() is to check the application id. When a failure occurs (e.g. the app ID is unexpected), you can throw an exception or use response.fail. For example:

```javascript
// Ensure it is our intended application sending the requests
alexaApp.pre = function (request, response, type) {
    if (request.sessionDetails.application.applicationId !== Config.applicationId) {
        // Fail ungracefully
        //console.log('Invalid applicationId: ' + request.sessionDetails.application.applicationId);
        //throw 'BAD_APP_ID';
        response.fail('Invalid applicationId: ' + request.sessionDetails.application.applicationId);
    }
};
```

**Comment by tekkkon** [comment]
thanks

**Comment by dblock** [comment]
Closing this. 

It would be helpful if someone could clarify this in README. Maybe @tekkkon?
