### ISSUE TITLE
how to handle built-in intents like AMAZON.StartOverIntent

### ISSUE THREAD

**Issue by dreed47** [matt-kruse/alexa-app#84]
How can I handle built-in intents like AMAZON.StartOverIntent?  When I define it like my custom intents it never seems to fire.

**Comment by teddis** [comment]
Just add the built-in intent you want to handle to your interaction model's intent schema:
```
{
     "intent": "AMAZON.HelpIntent",
     "slots": []
}
```

**Comment by dblock** [comment]
Closing this. @dreed47 please let us know if you're still having issues.
