### ISSUE TITLE
Sending response with <audio> tag

### ISSUE THREAD

**Issue by mdeyo** [matt-kruse/alexa-app#85]
Your 'to-ssml.js' function is cleansing the response text of <speech> and other tags, which prevents me from adding an <audio> tag in between speech. Is there another way to add audio, for example <audio src='https://hosting.website.sound.mp3'/>, to the response object?

**Comment by rickwargo** [comment]
Are you calling cleanse() - in that case the behavior is as designed. Otherwise, the audio tag should not be stripped from the SSML response. Can you provide a code sample?

**Comment by mdeyo** [comment]
I originally got it working with the following, instead of res.say():
'''
    res.response.response.outputSpeech = {
      "type": "SSML",
     "ssml": "<speak>Understood. <audio src='https://s3.amazonaws.com/noise.mp3' /></speak>"
    };
'''
Then I realized that it was the sound file format that was preventing res.say() from working. Converted it to be mp3 file at 16000, 48kbps, and static bit rate. The function works fine! Sorry for the confusion.
'''
    res.say("Understood. <audio src='https://s3.amazonaws.com/noise.mp3' />");
'''

The mp3 file conversion is described here: [https://developer.amazon.com/public/solutions/alexa/alexa-skills-kit/docs/speech-synthesis-markup-language-ssml-reference](https://developer.amazon.com/public/solutions/alexa/alexa-skills-kit/docs/speech-synthesis-markup-language-ssml-reference)

**Comment by rickwargo** [comment]
I was burned by the mp3 format, too, the first time. Thanks for the link.
