### ISSUE TITLE
Usage with alexa-sdk?

### ISSUE THREAD

**Issue by tayzlor** [matt-kruse/alexa-app#86]
Is anyone using this in combination with https://github.com/alexa/alexa-skills-kit-sdk-for-nodejs? 

I really like the local development approach with this but can see some advantages of the alexa-sdk (for example how it handles skill state management is much more advanced than this module).

**Comment by okofish** [comment]
I don't really see a way to combine the two - they both tackle the same problem, just in different ways. The abstracted state management is quite appealing, but I was able to implement a similar system in a recent skill with minimal overhead, by setting and clearing session attributes dynamically.

**Comment by tayzlor** [comment]
@okofish i'd come to the same conclusion. Have you got any sample/example code where you've implemented said similar system?

**Comment by matt-kruse** [comment]
Right, these are two solutions to the same problem. I created alexa-app long before the alexa-sdk ever existed.

**Comment by okofish** [comment]
@tayzlor [Here's](https://github.com/okofish/wheresmyphone/blob/master/functions/skill/index.js) a skill I just published with alexa-app, using rudimentary state tracking. I didn't bother to abstract it at all; it's just calls to request.session() to check the state and response.session() to set it - see lines [35](https://github.com/okofish/wheresmyphone/blob/73d5c714f3b3b833135d0658f18df268040c953e/functions/skill/index.js#L35) and [116](https://github.com/okofish/wheresmyphone/blob/73d5c714f3b3b833135d0658f18df268040c953e/functions/skill/index.js#L116) for example. Hopefully this helps you!

**Comment by tayzlor** [comment]
Thanks for the responses. Going to close this one.
