### ISSUE TITLE
Add a way to handle unknown Intents

### ISSUE THREAD

**Issue by OverloadUT** [matt-kruse/alexa-app#9]
From the docs, it doesn't seem like it's possible to capture an IntentRequest that doesn't match any of the registered Intents.

I think it'd be best to handle it using the same app.intent method, but with a null intent name:

```javascript
app.intent(null, function(request,response) {
    // Stuff to do if we get an unknown Intent!
});
```

**Comment by matt-kruse** [comment]
What do you want to do if you get an unknown intent? Currently, it will respond with the message in messages.NO_INTENT_FOUND, which by default is "Sorry, the application didn't know what to do with that intent". You can change this message to be anything you wish.

**Comment by OverloadUT** [comment]
It would depend on the application. For some I would just have it abort with no message. For others I might want to kick it over to a prompt for how to use the app.

Most importantly though, I'd want to log the event, as it's a programmer error if this ever happens!

**Comment by matt-kruse** [comment]
As noted in the other issue, you can catch the exception using app.error, then log and re-prompt the user if you wish. Does that work for you?

**Comment by OverloadUT** [comment]
That's certainly possible. It's an event that SHOULDN'T really happen, so relegating it to being part of the error handler can make sense.
