### ISSUE TITLE
Missing support for standard requests

### ISSUE THREAD

**Issue by pwbrown** [matt-kruse/alexa-app#96]
As far as I can tell from code and from testing, this <a href="https://github.com/matt-kruse/alexa-app/commit/e2b8c6c13fad9bec2c0ad5dbcaf899791c12a02d">commit</a> has unintentionally dropped support for standard requests. I was testing upgrading to latest in master today to try out the new AudioPlayer features and I found that none of my standard launch or intent requests would go through at all.  Started debugging and found on line 155 of index.js that "this.data.context" is undefined and produces a catch error that breaks execution.  The JSON structure for AudioPlayer requests includes the context attribute and as such is supported by the commit, but the original support for standard requests which include the session attribute was completely dropped.  Not sure how this was overlooked, but should be fixed.  I am running an alexa-app-server instance to debug locally.  If there is some obvious fix to this that I overlooked than it should probably be documented, but at the least the new commit should support legacy code.

**Comment by fremail** [comment]
@pwbrown are you testing your app with real requests? 
Amazon writes that **all** requests must contain _context_: [link](https://developer.amazon.com/public/solutions/alexa/alexa-skills-kit/docs/custom-standard-request-types-reference#request-examples)

**Comment by pwbrown** [comment]
Thanks @fremail I'll test with real requests in a bit. Either way alexa-app-server no longer works with latest in alexa-app on github and should probably be updated with the proper request JSON structure.

**Comment by fremail** [comment]
Oh, I just updated to the master and got an error for launch request:
`TypeError: Cannot read property 'application' of undefined`

I send a request JSON with `context`, but get `event` object w/o `context` object at all (in alexa.handler).

**Comment by pwbrown** [comment]
I just tested with the Alexa simulator and got a similar result.  Looks like it's on Amazon this time for not updating or not sending their full structure in the simulator request.  Tested the Alexa start structure that is prebuilt for testing Lambda functions and looks like they updated it to include the context structure so it ended up working.  Also tested it on the device itself and it worked fine.  I think in terms of this bug, it is probably resolved although I would say it could be adjusted so it doesn't hard fail in this circumstance, but that it gives a helpful error message.  As for now I will start writing a pull request to update the request structure for alexa-app-server since that is the main local testing tool I use.  Thanks @fremail for the quick feedback.

**Comment by fremail** [comment]
Got the same error even on a real request :(

**Comment by fremail** [comment]
Then we can't get `userId` and `applicationId` if the request w/o `session`. 

Don't understand how we should check `applicationId` in that case.

I can leave `userId` and `applicationId` empty in case of request doesn't have `session`. But I don't like that solution.

@dblock maybe you have alternative ideas?

**Comment by pwbrown** [comment]
Sifting through documentation for Alexa it seems that Amazon is very unclear about what is included in requests across the board.  AudioPlayer is very clear that the session object is not included and that the userId and applicationId is clearly found in the context object, but other pages either show the context object present along with the session object in standard requests or they aren't.  Why don't you just attempt to retrieve the userId and applicationId from context, and if that fails see if there is a session object that can be searched, and if that fails then don't include it.  From the documentation it seems that all requests will have one or the other or both in all cases.

**Comment by fremail** [comment]
I agree.

I'll fix that

**Comment by dblock** [comment]
I think for `applicationId` and such we should return `null` when there's no session.

**Comment by dblock** [comment]
I'm closing this via #100 and #101, @pwbrown would you be able to test against HEAD? Definitely want before releasing 2.4.0 (#103).
