### ISSUE TITLE
req.session throws "key not found on session attribute" 

### ISSUE THREAD

**Issue by cpup22** [matt-kruse/alexa-app#98]
I am trying to get a value from the session that isn't in the session:

req.session("keynotthere") and it throws 
key not found on session attributes: machine TypeError: Cannot read property 'keynotthere' of undefined

Which is fine but it won't continue to execute the logic in my code. I tried catching with a try catch but that doesn't work. I also tried printing out some messaging in the alexaapp.error method but it doesn't seem to get there.  I noticed there was another issue opened about try/catch handling, not sure if this is related.  

I mostly just want to check to see if the value exists in the session, if it does I handle, if it doesn't that's okay too.

**Comment by dblock** [comment]
This is on HEAD or in the released version?

Find out what that `undefined` is that throws the error?

The version on HEAD has made significant strides around session objects, has methods like `hasSession`, `session.get`, etc., and we should add a `hasKey` method to the session object as well to solve your issue permanently.

**Comment by cpup22** [comment]
released version I've been pulling/installing using npm.

**Comment by dblock** [comment]
@cpup22 It would be useful to try against HEAD, we've made a lot of code changes here. Maybe this is already fixed.

**Comment by dblock** [comment]
@cpup22 would like this confirmed as fixed/working on HEAD before releasing 2.4.0 (#103), will you be able to?

**Comment by dblock** [comment]
Thx @trayburn for a test, this is fixed on HEAD, closed.

**Comment by dblock** [comment]
@cpup22 Not yet, see https://github.com/matt-kruse/alexa-app/issues/103 there're other (potential) problems.

**Comment by dblock** [comment]
...but do try HEAD please
